---
- name: Cambio de Credenciales
  hosts: "{{ _host }}"
  become: yes
  vars:
    usuario: "{{ _usuario }}"
    passw: "{{ _pass }}"
    fecha: "{{ _fecha }}"

  
  tasks:
    - name: Cambiar la clave del usuario
      shell: |
        echo "{{ usuario }}:{{ passw }}" | chpasswd
      register: cambio_clave_result

    - name: Mostrar salida del cambio de clave
      debug:
        msg: "La salida es {{ cambio_clave_result }}"

    - name: Cambio de expiración de la "Clave"
      shell: |
        chuser -a expires={{ fecha }} {{ usuario }}
      register: cambio_expiracion_result
      debug:
        msg: "La expiracion del usuario {{ usuario }} es {{ cambio_expiracion_result.stdout }}"
  
    #- name: Mostrar la nueva clave (solo para fines de prueba)
    #  debug:
    #    msg: "Clave actualizada es: {{ passw }}"
