---
- name: Cambio de Credenciales
  hosts: "{{ _host }}"
  become: yes
  vars:
    usuario: "{{ _usuario }}"
    passw: "{{ _pass }}"
    fecha: "{{ _fecha }}"
    accion: "{{ _accion }}"  # Nueva variable: 'clave', 'fecha', o 'ambos'

  
  tasks:
    - name: Cambiar la clave del usuario
      shell: |
        echo "{{ usuario }}:{{ passw }}" | chpasswd
      register: cambio_clave_result
      when: accion == 'clave' or accion == 'ambos'

    - name: Mostrar salida del cambio de clave
      debug:
        msg: "La salida es {{ cambio_clave_result }}"
      when: accion == 'clave' or accion == 'ambos'

    - name: Cambio de expiración de la "Clave"
      shell: |
        chuser expires={{ fecha }} {{ usuario }}
      register: cambio_expiracion_result
      when: accion == 'fecha' or accion == 'ambos'

    - name: Mostrar salida del cambio de expiracion
      debug:
        msg: "La expiracion del usuario {{ usuario }} es {{ cambio_expiracion_result.stdout }}"
      when: accion == 'fecha' or accion == 'ambos'
