---
- name: Cambio de Credenciales
  hosts: "{{ _host }}"
  become: yes
  vars:
    usuario: "{{ _usuario }}"
    passw: "{{ _pass }}"

  
  tasks:
    - name: Cambiar la clave del usuario
      ansible.builtin.user:
        name: "{{ usuario }}"
        password: "{{ passw | password_hash('sha512') }}"
      register: cambio_clave_result

    - name: Mostrar salida del cambio de clave
      debug:
        msg: "La salida es {{ cambio_clave_result }}"

    - name: Confirmar cambio de clave
      debug:
        msg: "La clave del usuario {{ usuario }} ha sido cambiada."
  
    - name: Mostrar la nueva clave (solo para fines de prueba)
      debug:
        msg: "Clave actualizada para usuario {{ usuario }}"
