---
- name: Cambio de Credenciales
  hosts: 172.21.200.216
  become: yes
  vars:
    usuario: "rhormaza"
    nueva_clave: "NuevaClaveSegura123!"

  
  tasks:
    - name: Cambiar la clave del usuario
      ansible.builtin.user:
        name: "{{ usuario }}"
        password: "{{ nueva_clave | password_hash('sha512') }}"

    - name: Confirmar cambio de clave
      debug:
        msg: "La clave del usuario {{ usuario }} ha sido cambiada."
  
    - name: Mostrar la nueva clave (solo para fines de prueba)
      debug:
        msg: "La clave es {{ nueva_clave }}"
