---
- name: Cambio de Credenciales
  hosts: "{{ _host }}"
  become: yes
  vars:
    usuario: "{{ _usuario }}"
    fecha: "{{ _fecha }}"
    accion: "{{ _accion }}"  # Nueva variable: 'clave', 'fecha', o 'ambos'

  
  tasks:
    - name: Cambiar la clave del usuario
      shell: |
        clave=$(< /dev/urandom tr -dc 'A-Za-z0-9' | head -c 14)
        echo "{{ usuario }}:${clave}" | chpasswd
      register: cambio_clave_result
      no_log: true
      when: accion == 'clave' or accion == 'ambos'

    - name: Cambio de expiración de la "Clave"
      shell: |
        chuser expires={{ fecha }} {{ usuario }}
      register: cambio_expiracion_result
      when: accion == 'fecha' or accion == 'ambos'

    - name: Mostrar salida de los cambios de fecha
      debug:
        msg: 
          - "La expiracion del usuario: {{ usuario }} es {{ fecha }}"
      when: accion == 'fecha'

    - name: Mostrar salida de los cambios de clave
      debug:
        msg: 
          - "La clave del usuario: {{ cambio_clave_result.stdout }}"
      when: accion == 'clave'