---
- name: Creación Usuario en AIX
  hosts: "{{ _host }}"
  become: yes
  vars:
    usuario: "{{ _usuario }}"
    #passw: "{{ _pass }}"
    grupo: "{{ _grupo }}"
    grupo2: "{{ _grupo2 }}"
    id_usuario: "{{ _id_usuario }}"
    comment: "{{ _comment }}"
    home_dir: "{{ _home_dir }}"

  tasks:
    - name: Crear el usuario en AIX
      shell: |
        mkuser id={{ id_usuario }} pgrp={{ grupo }} groups={{ grupo2 }} home=/home/{{ home_dir }} comment="{{ comment }}" {{ usuario }}
      register: crear_usuario_result

    - name: Establecer la contraseña del usuario
      shell: |
        clave=$(< /dev/urandom tr -dc 'A-Za-z0-9' | head -c 14) &&
        echo "{{ usuario }}:{{ clave }}" | chpasswd
      register: establecer_contrasena_result

    - name: Mostrar salida de la creación del usuario y contraseña
      debug:
        msg: "Creación usuario resultado: {{ crear_usuario_result }}, Establecer contraseña resultado: {{ establecer_contrasena_result }}"