---
- name: Chequeo del estatus del Firewall
  hosts: all
  become: yes
  tasks:
    - name: Check if firewalld service is running
      service_facts:

    - name: Display firewall service status
      debug:
        msg: "Firewall service is {{ ansible_facts.services['firewalld.service'].state }}"
      when: "'firewalld.service' in ansible_facts.services"

    - name: Ensure firewalld is enabled and running
      service:
        name: firewalld
        state: started
        enabled: yes